[
  {name: 'ABC International Bank Plc'},
  {name: 'DB UK Bank Limited'},
  {name: 'Access Bank UK Limited'},
  {name: 'The ADIB (UK) Ltd'},
  {name: 'EFG Private Bank Limited'},
  {name: 'Ahli United Bank (UK) PLC'},
  {name: 'Europe Arab Bank plc'},
  {name: 'AIB Group (UK) Plc'},
  {name: 'Al Rayan Bank PLC'},
  {name: 'FBN Bank (UK) Ltd'},
  {name: 'Aldermore Bank Plc'},
  {name: 'FCE Bank Plc'},
  {name: 'Alliance Trust Savings Limited'},
  {name: 'FCMB Bank (UK) Limited'},
  {name: 'Allica Bank Ltd'},
  {name: 'Alpha Bank London Limited'},
  {name: 'Gatehouse Bank Plc'},
  {name: 'Arbuthnot Latham & Co Limited'},
  {name: 'Ghana International Bank Plc'},
  {name: 'Atom Bank PLC'},
  {name: 'Goldman Sachs International Bank'},
  {name: 'Axis Bank UK Limited'},
  {name: 'Guaranty Trust Bank (UK) Limited'},
  {name: 'Gulf International Bank (UK) Limited'},
  {name: 'Bank and Clients PLC'},
  {name: 'Bank Leumi (UK) plc'},
  {name: 'Habib Bank Zurich Plc'},
  {name: 'Bank Mandiri (Europe) Limited'},
  {name: 'Hampden & Co Plc'},
  {name: 'Bank Of Baroda (UK) Limited'},
  {name: 'Hampshire Trust Bank Plc'},
  {name: 'Bank of Beirut (UK) Ltd'},
  {name: 'Handelsbanken PLC'},
  {name: 'Bank of Ceylon (UK) Ltd'},
  {name: 'Havin Bank Ltd'},
  {name: 'Bank of China (UK) Ltd'},
  {name: 'HBL Bank UK Limited'},
  {name: 'Bank of Ireland (UK) Plc'},
  {name: 'HSBC Bank Plc'},
  {name: 'Bank of London and The Middle East plc'},
  {name: 'HSBC Private Bank (UK) Limited'},
  {name: 'Bank of New York Mellon (International) Limited'},
  {name: 'The HSBC Trust Company (UK) Ltd'},
  {name: 'Bank of Scotland plc'},
  {name: 'HSBC UK Bank Plc'},
  {name: 'Bank of the Philippine Islands (Europe) PLC'},
  {name: 'Bank Saderat Plc'},
  {name: 'ICBC (London) plc'},
  {name: 'Bank Sepah International Plc'},
  {name: 'ICBC Standard Bank Plc'},
  {name: 'Barclays Bank Plc'},
  {name: 'ICICI Bank UK Plc'},
  {name: 'Barclays Bank UK PLC'},
  {name: 'Investec Bank PLC'},
  {name: 'BFC Bank Limited'},
  {name: 'Itau BBA International PLC'},
  {name: 'Bira Bank Limited'},
  {name: 'BMCE Bank International plc'},
  {name: 'JN Bank UK Ltd'},
  {name: 'British Arab Commercial Bank Plc'},
  {name: 'J.P. Morgan Europe Limited'},
  {name: 'Brown Shipley & Co Limited'},
  {name: 'J.P. Morgan Securities plc'},
  {name: 'Jordan International Bank Plc'},
  {name: 'C Hoare & Co'},
  {name: 'Julian Hodge Bank Limited'},
  {name: 'CAF Bank Ltd'},
  {name: 'Cambridge & Counties Bank Limited'},
  {name: 'Kexim Bank (UK) Ltd'},
  {name: 'Cater Allen Limited'},
  {name: 'Kingdom Bank Ltd'},
  {name: 'Charity Bank Limited'},
  {name: 'The Charter Court Financial Services Limited'},
  {name: 'Lloyds Bank Plc'},
  {name: 'Chetwood Financial Limited'},
  {name: 'Lloyds Bank Corporate Markets Plc'},
  {name: 'China Construction Bank (London) Limited'},
  {name: 'CIBC World Markets Plc'},
  {name: 'Citibank UK Limited'},
  {name: 'ClearBank Limited'},
  {name: 'Close Brothers Limited'},
  {name: 'Clydesdale Bank Plc'},
  {name: 'Commonwealth Trade Bank Plc'},
  {name: 'The Co-operative Bank Plc'},
  {name: 'The Coutts & Company'},
  {name: 'Credit Suisse (UK) Limited'},
  {name: 'Credit Suisse International'},
  {name: 'Crown Agents Bank Limited'},
  {name: 'Cynergy Bank Limited'},
  {name: 'Macquarie Bank International Ltd'},
  {name: 'Tandem Bank Limited'},
  {name: 'Marks & Spencer Financial Services Plc'},
  {name: 'TD Bank Europe Limited'},
  {name: 'Masthaven Bank Limited'},
  {name: 'Tesco Personal Finance Plc'},
  {name: 'Melli Bank plc'},
  {name: 'Triodos UK Ltd'},
  {name: 'Methodist Chapel Aid Limited '},
  {name: 'TSB Bank plc'},
  {bank: 'Metro Bank PLC'},
  {bank: 'Turkish Bank (UK) Ltd'},
  {bank: 'Mizuho International Plc'},
  {name: 'Monzo Bank Ltd '},
  {name: 'Ulster Bank Ltd'},
  {name: 'Morgan Stanley Bank International Limited'},
  {name: 'Union Bank of India (UK) Limited'},
  {name: 'Union Bank UK Plc'},
  {name: 'National Bank of Egypt (UK) Limited'},
  {name: 'United Bank for Africa (UK) Limited'},
  {name: 'National Bank of Kuwait (International) Plc'},
  {name: 'United National Bank Limited'},
  {name: 'National Westminster Bank Plc'},
  {name: 'United Trust Bank Limited'},
  {name: 'NatWest Markets Plc'},
  {name: 'Unity Trust Bank Plc'},
  {name: 'Nomura Bank International Plc'},
  {name: 'Northern Bank Limited'},
  {name: 'Vanquis Bank Limited'},
  {name: 'Virgin Money plc'},
  {name: 'OakNorth Bank plc'},
  {name: 'VTB Capital plc'},
  {name: 'OneSavings Bank Plc'},
  {name: 'Weatherbys Bank Limited'},
  {name: 'Paragon Bank Plc'},
  {name: 'Wesleyan Bank Limited'},
  {name: 'PCF Bank Limited'},
  {name: 'Westpac Europe Ltd'},
  {name: 'Persia International Bank Plc'},
  {name: 'Wyelands Bank Plc'},
  {name: 'Philippine National Bank (Europe) Plc'},
  {name: 'Punjab National Bank (International)'},
  {name: 'Limited Zenith Bank (UK) Limited'},
  {name: 'Zopa Bank Limited'},
  {name: 'QIB (UK) Plc'},
  {name: 'R. Raphael & Sons Plc'},
  {name: 'Rathbone Investment Management Limited'},
  {name: 'RBC Europe Limited'},
  {name: 'RCI Bank UK Limited'},
  {name: 'Redwood Bank Ltd'},
  {name: 'Reliance Bank Ltd'},
  {name: 'Revver Limited'},
  {name: 'Royal Bank of Scotland Plc'},
  {name: 'The Sainsbury’s Bank Plc'},
  {name: 'Santander Financial Services plc'},
  {name: 'Santander UK Plc'},
  {name: 'State Bank Of India (UK) Limited'},
  {name: 'Schroder & Co Ltd'},
  {name: 'Scotiabank Europe Plc'},
  {name: 'Secure Trust Bank Plc'},
  {name: 'SG Kleinwort Hambros Bank Limited'},
  {name: 'Shawbrook Bank Limited'},
  {name: 'Sonali Bank (UK) Limited'},
  {name: 'Standard Chartered Bank'},
  {name: 'Starling Bank Limited'},
  {name: 'Sumitomo Mitsui Banking Corporation Europe Limited'},
];




